basePath: /
definitions:
  db.AddressComponents:
    properties:
      country:
        type: string
      district:
        type: string
      postalCode:
        type: string
      state:
        type: string
    type: object
  db.LatLong:
    description: LatLong struct
    properties:
      lat:
        type: number
      long:
        type: number
    required:
    - lat
    - long
    type: object
  db.LatLongGEOJson:
    description: dummy
    properties:
      coordinates:
        items:
          type: number
        type: array
      type:
        type: string
    type: object
  db.PlaceResult:
    properties:
      addressComponents:
        $ref: '#/definitions/db.AddressComponents'
      displayName:
        type: string
      formattedAddress:
        type: string
      googleMapsUri:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/db.LatLong'
      locationGEOJson:
        $ref: '#/definitions/db.LatLongGEOJson'
      nationalPhoneNumber:
        type: string
      rating:
        type: string
      shortFormattedAddress:
        type: string
      userRatingCount:
        type: string
      weekdayDescriptions:
        items:
          type: string
        type: array
    type: object
  router.APIError:
    properties:
      code:
        type: integer
      description:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: juampiq6@gmail.com
    name: Juampi Quinteros
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Nastapp
  version: "1.0"
paths:
  /gas_stations:
    get:
      description: lat and long parameters must be double
      parameters:
      - in: query
        name: lat
        required: true
        type: number
      - in: query
        name: long
        required: true
        type: number
      - description: Distance in meters
        in: query
        name: maxDistance
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.PlaceResult'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/router.APIError'
      summary: Lists all gas stations near a point restricted to a maximum distance
      tags:
      - gas_stations
swagger: "2.0"
